# set this to 'Retain' if you would like to retain state after spinning the cluster down
# and 'Delete' if you do not want to keep state
volumeRetainPolicy: Retain

confluence:
  image:
    repository: atlassian/confluence
    tag: latest
    pullPolicy: IfNotPresent

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi

  resources: {}

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  auth:
    username: admin
    password: localpassword
    database: confluencedb
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
