apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  annotations:
    # only 'keep' this resource if retain policy is set to 'Retain'
    {{- if eq .Values.volumeRetainPolicy "Retain" }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  # storageClassName: postgres-storage-class
  persistentVolumeReclaimPolicy: {{ .Values.volumeRetainPolicy }}  
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
