apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-confluence-volume
  annotations:
    # only 'keep' this resource if retain policy is set to 'Retain'
    {{- if eq .Values.confluence.persistence.volumeRetainPolicy "Retain" }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  persistentVolumeReclaimPolicy: {{ .Values.confluence.persistence.volumeRetainPolicy }}  
  accessModes:
    - {{ .Values.confluence.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.confluence.persistence.size }}
